// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    // Test name: Test1
    // Step # | name | target | value
    // 1 | open | /?app_key=9fb211ff9d4e64a7fc09fda6661d5ef7 | 
    driver.get("https://qaportal.intelligencenode.com/?app_key=9fb211ff9d4e64a7fc09fda6661d5ef7");
    // 2 | setWindowSize | 1552x832 | 
    driver.manage().window().setSize(new Dimension(1552, 832));
    // 3 | mouseOver | linkText=Items | 
    {
      WebElement element = driver.findElement(By.linkText("Items"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | linkText=Items | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | mouseOver | linkText=Categories | 
    {
      WebElement element = driver.findElement(By.linkText("Categories"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOut | linkText=Categories | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 7 | click | css=.nav > li:nth-child(3) > a | 
    driver.findElement(By.cssSelector(".nav > li:nth-child(3) > a")).click();
    // 8 | mouseDownAt | css=div:nth-child(1) > .catgoryFiltersDropdwon > .check-dd:nth-child(2) .newFeatureTooltip | -100.80000305175781,-280.9875183105469
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(1) > .catgoryFiltersDropdwon > .check-dd:nth-child(2) .newFeatureTooltip"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 9 | mouseMoveAt | css=.xAxisSection | 78.94998168945312,26.42498779296875
    {
      WebElement element = driver.findElement(By.cssSelector(".xAxisSection"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | mouseUpAt | css=.xAxisSection | 78.94998168945312,26.42498779296875
    {
      WebElement element = driver.findElement(By.cssSelector(".xAxisSection"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 11 | click | css=.relationshio-module > .row | 
    driver.findElement(By.cssSelector(".relationshio-module > .row")).click();
    // 12 | mouseDownAt | css=div:nth-child(1) > .catgoryFiltersDropdwon > .check-dd:nth-child(2) .newFeatureTooltip | -105.80000305175781,-415.98748779296875
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(1) > .catgoryFiltersDropdwon > .check-dd:nth-child(2) .newFeatureTooltip"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 13 | mouseMoveAt | css=.row:nth-child(8) | 101.75,201.22500610351562
    {
      WebElement element = driver.findElement(By.cssSelector(".row:nth-child(8)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | mouseUpAt | css=.row:nth-child(8) | 101.75,201.22500610351562
    {
      WebElement element = driver.findElement(By.cssSelector(".row:nth-child(8)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 15 | click | css=.relationshio-module > .row | 
    driver.findElement(By.cssSelector(".relationshio-module > .row")).click();
  }
}
